/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract hardware sets from a specification PDF. */
        post: operations["extract_endpoint_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{pdf_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A stored extraction: the corrected result if there is one. */
        get: operations["get_document_documents__pdf_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{pdf_hash}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Store a corrected result; the PDF returns it from now on. */
        put: operations["put_correction_documents__pdf_hash__corrections_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{pdf_hash}/pages/{page}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A page with the box and number of each set on it. */
        get: operations["get_page_image_documents__pdf_hash__pages__page__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_endpoint_extract_post */
        Body_extract_endpoint_extract_post: {
            /**
             * File
             * @description Specification PDF.
             */
            file: string;
        };
        /**
         * BookCode
         * @description An entry in the book's own code table: ("option", "EC2", "Flush Endcap").
         */
        BookCode: {
            /** Kind */
            kind: string;
            /** Code */
            code: string;
            /** Meaning */
            meaning: string;
            location: components["schemas"]["Location"] | null;
        };
        /** Component */
        Component: {
            /** Qty */
            qty: number | null;
            /** Unit */
            unit: string | null;
            /** Description */
            description: string;
            /** Catalog Number */
            catalog_number: string | null;
            /** Mfr */
            mfr: string | null;
            /** Finish */
            finish: string | null;
            /** Notes */
            notes: string | null;
            /** Mfr Normalized */
            mfr_normalized: string | null;
            /** Finish Normalized */
            finish_normalized: string | null;
            /** Confidence */
            confidence: {
                [key: string]: components["schemas"]["Confidence"];
            };
            /** Warnings */
            warnings: string[];
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "found" | "ambiguous" | "suspect";
        /** ExtractionResult */
        ExtractionResult: {
            /** Filename */
            filename: string | null;
            /** Page Count */
            page_count: number;
            /** Hardware Pages */
            hardware_pages: number[];
            /** Sets */
            sets: components["schemas"]["HardwareSet"][];
            /** Code Tables */
            code_tables: components["schemas"]["BookCode"][];
            /** Unresolved Codes */
            unresolved_codes: {
                [key: string]: string[];
            };
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /**
             * Batch Tokens
             * @default {}
             */
            batch_tokens: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            /** Pdf Hash */
            pdf_hash?: string | null;
            /**
             * Corrected
             * @default false
             */
            corrected: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardwareSet */
        HardwareSet: {
            /** Set Number */
            set_number: string | null;
            /** Description */
            description: string | null;
            /** Not Used */
            not_used: boolean;
            /** Openings */
            openings: string[];
            /** Location */
            location: components["schemas"]["Location"][];
            /** Components */
            components: components["schemas"]["Component"][];
            /** Notes */
            notes: string[];
            /** Operation */
            operation: string | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * Location
         * @description A box on a page, in points from the page's top-left, like Word and Line:
         *     x = (left, right), y = (top, bottom).
         */
        Location: {
            /** Page */
            page: number;
            /** X */
            x: [
                number,
                number
            ];
            /** Y */
            y: [
                number,
                number
            ];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_endpoint_extract_post: {
        parameters: {
            query?: {
                /** @description Half price via Anthropic's Batch API; up to an hour. */
                batch?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_endpoint_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Batch mode: still running; POST the same PDF again. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__pdf_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pdf_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_correction_documents__pdf_hash__corrections_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pdf_hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_image_documents__pdf_hash__pages__page__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pdf_hash: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
